INSERT INTO Users (UserID, Name, PoliticalParty, Bio) VALUES
  (1, 'Bea Annell', 'Party of the European Left', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam'),
  (2, 'Amery Glancey', 'European Democratic Party', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus'),
  (3, 'Sofie Ianizzi', 'Party of the European Left', 'porttitor pede justo eu massa donec dapibus duis at velit eu'),
  (4, 'Orsa Torrent', 'European People''s Party', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci'),
  (5, 'Elfreda Morrel', 'European Free Alliance', 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis'),
  (6, 'Muffin Rousel', 'European Free Alliance', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus'),
  (7, 'Bogey Cummine', 'European Democratic Party', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh'),
  (8, 'Currie Storrar', 'European Democratic Party', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est'),
  (9, 'Bennie Ebbing', 'European People''s Party', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit'),
  (10, 'Anestassia Marcombe', 'Party of European Socialists', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae'),
  (11, 'Jarret McGrorty', 'European Free Alliance', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a'),
  (12, 'Elmore Deem', 'European Democratic Party', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices'),
  (13, 'Teador Beville', 'Party of European Socialists', 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper'),
  (14, 'Stephanus Humphris', 'European Green Party', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque'),
  (15, 'Marietta Maskall', 'Party of the European Left', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus'),
  (16, 'Annmaria Philipot', 'European People''s Party', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec'),
  (17, 'Yvette Norquay', 'Party of European Socialists', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis'),
  (18, 'Neall Whittington', 'European People''s Party', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis');
